# CircOrf-config-file
# This configuration file includes all adjustable options and files for CircOrf.
# Please input full absolute path.
# You can submit your question by submitting issue on github or sending an e-mail
# E-mail = mr1997@snnu.edu.cn
# Date = 30 July 2021

# The genome name of your program
genome_name: MrGenome

#################
# required data #
#################

# The path of genome file
genome_fasta: /home/li/public/mr/data/Human-example/Homo_sapiens.GRCh38.dna_sm.toplevel.fa

# The path of gtf file of genome
genome_gtf: /home/li/public/mr/data/Human-example/Homo_sapiens.GRCh38.104.gtf

# The path of ribo-seq raw reads file
raw_reads: 
           - /home/li/public/mr/data/Human-example/SRR5680924.sra

# The path of ribosome sequence file
ribosome_fasta: /home/li/public/mr/data/Human-example/human_rRNA.fa

# The path of Candidate circRNA
circrnas: /home/li/public/mr/CircOrf_test/CircOrf1122/transcirc_sequence.fasta
#/home/li/public/mr/data/Human-example/human_hg19_circRNAs_putative_spliced_sequence.fa

# The path of gtf file of circRNA, the file should be generated in our way(README.md) 
circrna_gtf: circ_ref.csv

#####################
# Required location #
#####################

# The path of folder for storing the final result
result_file_location: /home/li/public/mr/CircOrf_test/CircOrf1122/CircOrf/SRR5680924_0_result

# The path of folder for storing temporary results
tmp_file_location: /home/li/public/mr/CircOrf_test/CircOrf1122/CircOrf/SRR5680924_0_tmp

################################
# Adjustable filter parameters #
################################

# Coverage counts, DEFAULT = 10.
coverage_counts: 3

# The thread to run tophat2 and SEPCtr, DEFAULT = 6
thread: 12

#################
# OTHER OPTIONS #
#################

# The path of trimmomatic.jar
trimmomatic_jar: ./requiredSoft/trimmomatic-0.38.jar

# The path of adapters file
riboseq_adapters: ./requiredSoft/riboseq-adapters.fa

# The path of your train_pos.fa for M6A, DEFAULT = default_path
pos_fa: default_path

# The path of your train_neg.fa for M6A, DEFAULT = default_path
neg_fa: default_path

# The type of reads, please input single or pair
reads_type: single

# type of Ribo-seq data, value: sra or fastq.gz 
ribotype: sra




