# CircOrf-config-file
# This configuration file includes all adjustable options and files for CircOrf.
# Please input full absolute path.
# You can submit your question by submitting issue on github or sending an e-mail
# E-mail = mr1997@snnu.edu.cn
# Date = 30 July 2021

# The genome name of your program
genome_name: MrGenome

#################
# required data #
#################

# The path of genome file
genome_fasta: /full/absolute/path

# The path of gtf file of genome
genome_gtf: /full/absolute/path

# The path of ribo-seq raw reads file
raw_reads: 
           - /full/absolute/path

# The path of ribosome sequence file
ribosome_fasta: /full/absolute/path

# The path of Candidate circRNA
circrnas: /full/absolute/path

# The path of gtf file of circRNA
circrna_gtf: /full/absolute/path

# The path of adapters file
riboseq_adapters: ./requiredSoft/riboseq-adapters.fa

#####################
# Required location #
#####################

# The path of folder for storing the final result
result_file_location: /full/absolute/path

# The path of folder for storing temporary results
tmp_file_location: /full/absolute/path

################################
# Adjustable filter parameters #
################################

# Coverage counts, DEFAULT = 10.
coverage_counts: 2

# The thread to run tophat2 and SEPCtr, DEFAULT = 6
thread: 12

#please input the IRES region lenth of the ORF upstream that you need
lenth_need: 100

#please input the IRES score of the upstream sequence(0-1)
ires_score: 0.5

#please input the ORF score of  the ORF sequence(0-1)
orf_score: 0.5

#################
# OTHER OPTIONS #
#################

# The path of trimmomatic.jar
trimmomatic_jar: ./requiredSoft/trimmomatic-0.38.jar

# The type of reads, please input single or pair
reads_type: single

# type of Ribo-seq data, value: sra or fastq.gz 
ribotype: sra




